# Generated by Django 5.0 on 2023-12-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('likes', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
